---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
      become: yes
  tasks:
    - name: Install so deps
      apt:
        name:
          - php7.2
          - apache2
          - libapache2-mod-php7.2
          - php7.2-gd
          - php-ssh2
          - libmcrypt4
          - mysql-server-5.7
          - python3-mysqldb
          - php7.2-mysql
        state: latest
        update_cache: yes
      become: yes
    - name: Create database
      mysql_db:
        name: wordpress_db
        login_user: root
        state: present
      become: yes
    - name: Create db user
      mysql_user:
        login_user: root
        name: wordpress_user
        password: wordpress_user@password
        priv: 'wordpress_db.*:ALL'
        state: present
      become: yes
    - name: Download latest wordpress
      get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress.tar.gz'
    - name: Decompress wordpress into /var/www
      unarchive:
        remote_src: yes
        src: /tmp/wordpress.tar.gz
        dest: /var/www
      become: yes
    - name: Add wp-config.php
      copy:
        src: /var/www/wordpress/wp-config-sample.php
        dest: /var/www/wordpress/wp-config.php
        remote_src: yes
      become: yes
    - name: Edit wp-config
      replace:
        path: '/var/www/wordpress/wp-config.php'
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      with_items:
        - { regex: 'username_here', value: 'wordpress_user' }
        - { regex: 'database_name_here', value: 'wordpress_db' }
        - { regex: 'password_here', value: 'wordpress_user@password' }
      become: yes
    - name: Add wordpress to apache site-available
      copy:
        src: 'files/000-default.conf'
        dest: /etc/apache2/sites-available/000-default.conf
      become: yes
      notify:
        - restart apache
