---
- hosts: database
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - mysql

- hosts: wordpress
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - wordpress
