---
- hosts: all
  tasks:
    - name: Install so deps
      apt:
        name:
          - php5
          - apache2
          - libapache2-mod-php5
          - php5-gd
          - libssh2-php
          - php5-mcrypt
          - mysql-server-5.6
          - python-mysqldb
          - php5-mysql
        state: latest
      become: yes
    - name: Create database
      mysql_db:
        name: wordpress_db
        login_user: root
        state: present
    - name: Create db user
      mysql_user:
        login_user: root
        name: wordpress_user
        password: wordpress_user@password
        priv: 'wordpress_db.*:ALL'
        state: present
    - name: Download latest wordpress
      get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress1.tar.gz'
    - name: Decompress wordpress into /var/www
      unarchive:
        remote_src: yes
        src: /tmp/wordpress.tar.gz
        dest: /var/www
      become: yes
    - name: Add wp-config.php
      copy:
        src: /var/www/wordpress/wp-config-sample.php
        dest: /var/www/wordpress/wp-config.php
        remote_src: yes
      become: yes

    - name: Edit wp-config
      replace:
        path: '/var/www/wordpress/wp-config.php'
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      with_items:
        - { regex: 'username_here', value: 'wordpress_user' }
        - { regex: 'database_name_here', value: 'wordpress_db' }
        - { regex: 'password_here', value: 'wordpress_user@password' }
      become: yes
