---
- name: Download latest wordpress
  get_url:
    url: 'https://wordpress.org/latest.tar.gz'
    dest: '/tmp/wordpress.tar.gz'
- name: Decompress wordpress into /var/www
  unarchive:
    remote_src: yes
    src: /tmp/wordpress.tar.gz
    dest: /var/www
  become: yes
- name: Add wp-config.php
  copy:
    src: "{{ wp_installation_dir }}/wp-config-sample.php"
    dest: "{{ wp_installation_dir }}/wp-config.php"
    remote_src: yes
  become: yes
- name: Edit wp-config
  replace:
    path: "{{ wp_installation_dir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items:
    - { regex: 'username_here', value: "{{ wp_db_username }}" }
    - { regex: 'database_name_here', value: "{{ wp_db_name }}" }
    - { regex: 'password_here', value: "{{ wp_db_password }}" }
    - { regex: 'localhost', value: "{{ wp_db_host }}" }
  become: yes
- name: Configure apache to serve wordpress
  template:
    src: 'templates/000-default.conf.j2'
    dest: /etc/apache2/sites-available/000-default.conf
  become: yes
  notify:
    - restart apache
