---
- name: Install db dependencies
  apt:
    name:
      - mysql-server-5.7
      - python3-mysqldb
    state: present
  become: yes

- name: Create database
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: root
    state: present
  become: yes

- name: Create db user
  mysql_user:
    login_user: root
    name: "{{ wp_db_username }}"
    password: "{{ wp_db_password }}"
    priv: '{{ wp_db_name }}.*:ALL'
    state: present
    host: "{{ item }}"
  with_items:
    - localhost
    - 127.0.0.1
    - "{{ wp_host_ip }}"
  become: yes
- name: Update mysql bind-address
  copy:
    src: files/my.cnf
    dest: /etc/mysql/my.cnf
  become: yes
  notify:
    - restart mysql


